inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Style/AlignParameters:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingComma:
  Enabled: false
