language: ruby
cache: bundler
sudo: false
rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - jruby-9.1.9.0
gemfile:
  - gemfiles/ar50.gemfile
  - gemfiles/ar51.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.1.9.0
