language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - jruby-9.1.9.0
gemfile:
  - gemfiles/ar50.gemfile
  - gemfiles/ar51.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.1.9.0
